version: '3.5'

services:
  postgres:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:${DB_PORT}'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    container_name: raffle-db
    volumes:
      - ./postgres:/var/lib/postgresql/data
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      # Host- Contenedor
      - '3001:3000'
    volumes:
      - ./api/src:/app/src
      - node_modules:/app/node_modules
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      NODE_ENV: development
      DISCORD_PUBLIC_KEY: ${DISCORD_PUBLIC_KEY}
volumes:
  node_modules:
